baseURL = 'http://localhost:8080/'
languageCode = 'de'
title = 'Thomas Juhnke — Softwareentwickler'

# empty taxonomies will *NOT* generate "categories" or "tags" taxonomy pages
[taxonomies]

[params]
    description = 'Individuelle Softwareentwicklung, Qualitätssicherung und Beratung für kleine bis mittelgroße Softwareprojekte.'

[params.vcard]
    portrait = 'Thomas-Juhnke_portrait-casual.jpg'
    firstName = 'Thomas'
    lastName = 'Juhnke'
    position = 'Software­entwickler'

[params.footer.auxiliaryLinks.0]
    icon = 'bi-linkedin'
    url = 'https://www.linkedin.com/in/thomas-juhnke'
    title = 'LinkedIn Profil'