version: '3'

services:
  gatsby:
    image: dreadlabs/node:lts-debian
    volumes:
      - ./:/app:cached
    working_dir: /app
    ports:
      - 8000:8000
      - 3001:3001
      - 35729:35729
    command: ["npm", "run", "develop", "--", "--host=0.0.0.0"]
