version: '3'

services:
  gatsby:
    image: dreadlabs/node-yarn:6.11
    volumes:
      - ./:/app
    ports:
      - 8000:8000
      - 3001:3001
      - 35729:35729
    command: ["sh", "-c", "yarn", "run", "develop"]
