#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f composer.json ]; then
    docker run --rm --env LOCAL_USER_ID="$(id -u "$USER")" --volume "$(pwd)":/app dreadlabs/composer:1.3.1 composer install --optimize-autoloader --no-ansi --no-interaction
else
    echo "==> No composer.json found in root directory. Please run script/init."
    exit 1
fi
