#!/bin/sh

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
    if [ "$1" = "node" ]; then
        docker run --interactive --tty --rm --env LOCAL_USER_ID="$(id -u "$USER")" --volume "$(pwd)":/app dreadlabs/node-yarn:6.11 /bin/bash
    else
        echo "==> Sorry, I don't known how to connect to the '$1' environment."
        exit 1
    fi
else
    # no argument provided, so just run the local console in the development
    # environment. Ensure the application is up to date first.
    script/update
    docker run --interactive --tty --rm --env LOCAL_USER_ID="$(id -u "$USER")" --volume "$(pwd)":/app dreadlabs/node-yarn:6.11 /bin/bash
fi
