#!/bin/sh

# script/init: Initializes a new project

set -e

cd "$(dirname "$0")/.."

# git config --global user.email "dev@dreadlabs.de"
# git config --global user.name "Thomas Juhnke"

echo "==> Project already initialized."
exit 1
