#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

docker run --rm --env LOCAL_USER_ID="$(id -u "$USER")" --volume "$(pwd)":/app --workdir /app dreadlabs/php-lib:7.0-dev composer update --optimize-autoloader --no-ansi --no-interaction
